"use client";

/**
 * P12Ch04 · Section 3 — "Key Formulas and Definitions"
 * Beats (en [0,1,3,4,6,10,11]): 7 beats
 */

import React from "react";
import {
  SceneProps, useBeat, delayFor, Fade, Draw, T, Chip, ringD,
  INK, MUTED, AMBER_DARK, GREEN, RED, CREAM,
} from "./kit";

function Badge({ n, cx, cy, on, delay }: { n: number; cx: number; cy: number; on: boolean; delay: number }) {
  return (
    <g>
      <Draw on={on} delay={delay}
        d={`M ${cx - 13} ${cy} A 13 13 0 1 1 ${cx + 13} ${cy} A 13 13 0 1 1 ${cx - 13} ${cy}`}
        stroke={RED} sw={2.2} dur={0.4} />
      <Fade on={on} delay={delay + 0.3}>
        <T x={cx} y={cy + 5} size={14} fill={RED} weight={800}>{n}</T>
      </Fade>
    </g>
  );
}

export default function P12Ch04Sec3({ currentTime, reveals, language }: SceneProps) {
  const beat = useBeat(currentTime, reveals);
  const en = language === "english";
  const t = (e: string, h: string) => (en ? e : h);
  const dl = (k: number, d: number) => delayFor(beat, k, d);

  return (
    <svg viewBox="0 0 1080 620" preserveAspectRatio="xMidYMin meet" className="w-full h-full select-none">
      {/* Title */}
      <Fade on={beat >= 0} delay={dl(0, 0.4)}>
        <T x={540} y={48} size={25} fill={RED} script>
          {t("Key Formulas & Definitions: Biot-Savart & Field Results", "Key Formulas & Definitions: Biot-Savart & Field Results")}
        </T>
      </Fade>
      <Draw on={beat >= 0} delay={dl(0, 2.5)} d="M 120 60 C 420 56, 660 64, 960 59" stroke={RED} sw={2.4} dur={0.7} />

      {/* LEFT SECTION: BIOT-SAVART LAW */}
      <g transform="translate(40, 75)">
        <Badge n={1} cx={20} cy={18} on={beat >= 1} delay={dl(1, 0.2)} />
        <Fade on={beat >= 1} delay={dl(1, 0.5)}>
          <T x={45} y={23} size={15} fill={RED} weight={800} anchor="start">
            {t("BIOT-SAVART LAW DIFFERENTIAL FORMULA", "BIOT-SAVART LAW DIFFERENTIAL FORMULA")}
          </T>
        </Fade>

        {/* Floating Solution Steps */}
        <Fade on={beat >= 1}>
          <T x={45} y={80} size={14} fill={AMBER_DARK} weight={800} anchor="start">
            1. Vector Form: dB = (μ₀ / 4π) (I dl × r̂) / r².
          </T>

          <T x={45} y={125} size={14} fill={INK} weight={800} anchor="start">
            2. Scalar Magnitude: |dB| = (μ₀ / 4π) (I dl sin θ / r²).
          </T>

          <T x={45} y={170} size={14} fill={GREEN} weight={800} anchor="start">
            3. Permeability Constant: μ₀ / 4π = 10⁻⁷ T·m/A.
          </T>

          <Draw on={beat >= 4} delay={dl(4, 1.2)} d="M 45 195 L 450 195" stroke={INK} sw={1.8} />

          <T x={45} y={235} size={16} fill={RED} weight={900} anchor="start">
            4. Permeability Value: μ₀ = 4π × 10⁻⁷ N/A² !
          </T>
        </Fade>

        <Fade on={beat >= 4}>
          <T x={45} y={268} anchor="start" size={13} fill={INK} weight={800}>
            (Governs magnetic field generated by any current element I dl)
          </T>
        </Fade>
      </g>

      {/* RIGHT SECTION: STANDARD FIELD RESULTS */}
      <g transform="translate(540, 75)">
        <Badge n={2} cx={20} cy={18} on={beat >= 4} delay={dl(4, 0.2)} />
        <Fade on={beat >= 4} delay={dl(4, 0.5)}>
          <T x={45} y={23} size={15} fill={RED} weight={800} anchor="start">
            {t("STANDARD WIRE & LOOP FIELD RESULTS", "STANDARD WIRE & LOOP FIELD RESULTS")}
          </T>
        </Fade>

        {/* Floating Solution Steps */}
        <Fade on={beat >= 4}>
          <T x={45} y={80} size={14} fill={AMBER_DARK} weight={800} anchor="start">
            1. Infinite Straight Wire: B = μ₀ I / (2π a).
          </T>

          <T x={45} y={125} size={14} fill={GREEN} weight={800} anchor="start">
            2. Finite Wire: B = (μ₀ I / 4π a) (sin θ₁ + sin θ₂).
          </T>

          <T x={45} y={170} size={14} fill={RED} weight={800} anchor="start">
            3. Circular Loop Center: B = μ₀ I / (2 R).
          </T>

          <Draw on={beat >= 10} delay={dl(10, 1.2)} d="M 45 195 L 450 195" stroke={INK} sw={1.8} />

          <T x={45} y={235} size={16} fill={GREEN} weight={900} anchor="start">
            4. On-Axis Loop Field: B_axis = μ₀ I R² / [2(x² + R²)³/²] !
          </T>
        </Fade>

        <Fade on={beat >= 10}>
          <T x={45} y={268} anchor="start" size={13} fill={GREEN} weight={800}>
            (For N turns, multiply any loop formula by N)
          </T>
        </Fade>
      </g>

      {/* LOWER SECTION: OPEN SPACIOUS SUMMARY */}
      <g transform="translate(40, 415)">
        <Badge n={3} cx={20} cy={18} on={beat >= 10} delay={dl(10, 0.2)} />
        <Fade on={beat >= 10} delay={dl(10, 0.5)}>
          <T x={45} y={23} size={15} fill={RED} weight={800} anchor="start">
            {t("BIOT-SAVART MASTER FORMULAS VERDICT", "BIOT-SAVART MASTER FORMULAS VERDICT")}
          </T>
        </Fade>

        <Fade on={beat >= 10}>
          <T x={45} y={50} size={14} anchor="start" fill={GREEN} weight={800}>
            Biot-Savart Law dB = (μ₀ / 4π) (I dl × r̂) / r² is the fundamental building block for magnetostatics.
          </T>
          <T x={45} y={72} size={13} anchor="start" fill={INK} weight={700}>
            Master Results: Infinite wire B = μ₀I/(2πa); Circular loop center B = μ₀I/(2R); On-axis B = μ₀IR² / 2(x²+R²)³/².
          </T>
        </Fade>
      </g>

      {/* Footer Summary Chip (Floating without card boxes) */}
      <Fade on={beat >= 10}>
        <Chip x={40} y={545} w={1000} h={46} fill={GREEN} textFill="#ffffff" size={14}>
          {t(
            "★ Master formulas: Infinite wire B = μ0I/2πa | Loop center B = μ0I/2R | On-axis B = μ0IR²/2(x²+R²)³/²! ✓",
            "★ Master formulas: Infinite wire B = μ0I/2πa | Loop center B = μ0I/2R | On-axis B = μ0IR²/2(x²+R²)³/²! ✓"
          )}
        </Chip>
      </Fade>
    </svg>
  );
}
